/**
 * Exponential ElGamal on BabyJubJub, in JavaScript.
 *
 * This is the off-chain counterpart to `circuits/src/elgamal.circom` (in-circuit) and
 * `contracts/src/ElGamalAccumulator.sol` (on-chain). All three must agree, for the same
 * reason `atrum.mjs` documents about the hashing rules: if they diverge, proofs fail at
 * verification with no diagnostic while every gas number still looks fine.
 *
 * It lives here rather than inside `prove.mjs` because two consumers need it and they
 * must not drift:
 *
 *   - `prove.mjs` verifies the mechanism -- that the circuit encodes the scheme we think
 *     it does, and that the homomorphic property actually holds.
 *   - the publisher decrypts the accumulated pool total on a cadence.
 *
 * A second independent implementation of `decrypt` would be a correctness risk with no
 * upside: the publisher's decryption is what payouts derive from, so if it disagreed
 * with the one the mechanism was verified against, nothing would catch it.
 *
 * KEY HANDLING. `buildElGamal` takes the secret optionally. Encryption needs only the
 * public key, so anything that just encrypts (fixture generation, tests) passes the
 * public half alone and physically cannot decrypt. `decrypt` throws rather than
 * misbehaving if the secret is absent.
 */
import { buildBabyjub } from "circomlibjs";

/**
 * `crypto.getRandomValues` rather than `node:crypto`, because this module is bundled for
 * the browser client as well as run under Node. It is the same CSPRNG on both: globalThis
 * `crypto` is standard in Node 19+ and in every browser.
 *
 * This must stay cryptographically secure. The encryption randomness `r` it produces is
 * what hides the stake -- `encRandomness = 0` makes C1 the identity and C2 = [units]G, so
 * anyone recovers the bet by discrete log. The circuit and the contract both guard against
 * zero, but a weak RNG here would be silent.
 */
function randomBytes32() {
  return crypto.getRandomValues(new Uint8Array(32));
}

const toHex = (bytes) =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");

/**
 * Order of the BabyJubJub prime-order subgroup generated by Base8.
 *
 * Scalars are drawn from here, not from the full curve order: a scalar outside the
 * subgroup can land on a small-order point, and for the encryption randomness `r` that
 * would leak the plaintext.
 */
export const SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

/**
 * @param pubKey  committee public key H, as [x, y] (bigint or decimal string)
 * @param secret  committee secret s, or null for an encrypt-only instance
 */
export async function buildElGamal(pubKey, secret = null) {
  const babyJub = await buildBabyjub();
  const F = babyJub.F;

  const H = [F.e(BigInt(pubKey[0])), F.e(BigInt(pubKey[1]))];
  const s = secret === null ? null : BigInt(secret);

  /** The twisted-Edwards identity is (0, 1), not the point at infinity. */
  const IDENTITY = [F.e(0n), F.e(1n)];

  /** On a twisted Edwards curve, -(x, y) = (-x, y). */
  const negate = (p) => [F.neg(p[0]), p[1]];

  const asPair = (p) => [F.toObject(p[0]), F.toObject(p[1])];
  const samePoint = (a, b) => F.eq(a[0], b[0]) && F.eq(a[1], b[1]);

  /** Uniform scalar in [1, SUBGROUP_ORDER). Rejection sampled, never reduced. */
  function randomScalar() {
    while (true) {
      const c = BigInt("0x" + toHex(randomBytes32()));
      if (c > 0n && c < SUBGROUP_ORDER) return c;
    }
  }

  /**
   * C1 = [r]G, C2 = [m]G + [r]H.
   *
   * `mulPointEscalar` returns the identity for scalar 0 in circomlibjs, but m = 0 is
   * spelled out explicitly here because it is the edge case the complete addition law
   * exists to handle and it is exercised by `prove.mjs`.
   */
  function encrypt(m, r) {
    const c1 = babyJub.mulPointEscalar(babyJub.Base8, r);
    const mG = m === 0n ? IDENTITY : babyJub.mulPointEscalar(babyJub.Base8, m);
    const rH = babyJub.mulPointEscalar(H, r);
    return { c1, c2: babyJub.addPoint(mG, rH) };
  }

  /** Ciphertext addition -- exactly what ElGamalAccumulator.sol does on-chain. */
  function addCiphertext(a, b) {
    return {
      c1: babyJub.addPoint(a.c1, b.c1),
      c2: babyJub.addPoint(a.c2, b.c2),
    };
  }

  /**
   * Recover m from a ciphertext: [m]G = C2 - [s]C1, then discrete log by
   * baby-step giant-step.
   *
   * BSGS is why plaintexts must be range-bounded. It is O(sqrt(bound)), so the
   * publisher can recover a pool total of ~2^40 in ~2^20 steps, but the cost grows
   * as the square root of the bound -- an unbounded plaintext is unrecoverable.
   */
  function decrypt(c1, c2, bound) {
    if (s === null) {
      throw new Error("decrypt requires the committee secret; this instance is encrypt-only");
    }

    const target = babyJub.addPoint(c2, negate(babyJub.mulPointEscalar(c1, s)));
    if (samePoint(target, IDENTITY)) return 0n;

    const m = BigInt(Math.ceil(Math.sqrt(Number(bound))) + 1);

    // Baby steps: table of [j]G for j in [0, m).
    const table = new Map();
    let acc = IDENTITY;
    for (let j = 0n; j < m; j++) {
      table.set(`${F.toObject(acc[0])},${F.toObject(acc[1])}`, j);
      acc = babyJub.addPoint(acc, babyJub.Base8);
    }

    // Giant steps: target - [i*m]G, looking for a baby step.
    const negMG = negate(babyJub.mulPointEscalar(babyJub.Base8, m));

    let cur = target;
    for (let i = 0n; i <= m; i++) {
      const hit = table.get(`${F.toObject(cur[0])},${F.toObject(cur[1])}`);
      if (hit !== undefined) return i * m + hit;
      cur = babyJub.addPoint(cur, negMG);
    }
    throw new Error("BSGS failed -- plaintext outside the searched bound");
  }

  return {
    babyJub,
    F,
    H,
    IDENTITY,
    encrypt,
    decrypt,
    addCiphertext,
    randomScalar,
    negate,
    asPair,
    samePoint,
  };
}
